# Generated by Django 3.2.8 on 2021-10-23 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='one_question',
            fields=[
                ('field_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('next', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('Autocomplete', 'Autocomplete'), ('Checkbox', 'Checkboxe'), ('Chips', 'Chips'), ('Picker', 'Picker'), ('Radio', 'Radio'), ('Range', 'Range'), ('Select', 'Select'), ('Switch', 'Switch'), ('Input', 'Input'), ('Switch', 'Switch')], default='Input', max_length=20, verbose_name='type_choices')),
                ('choices', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='one',
            fields=[
                ('age_range', models.CharField(blank=True, max_length=30, null=True)),
                ('describe', models.JSONField(blank=True, default=dict, null=True)),
                ('desire', models.JSONField(blank=True, max_length=350, null=True)),
                ('listen', models.CharField(blank=True, max_length=100, null=True)),
                ('teachable', models.IntegerField(blank=True, null=True)),
                ('willing', models.CharField(blank=True, max_length=70, null=True)),
                ('change', models.CharField(blank=True, max_length=350, null=True)),
                ('meeting', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lead.lead_model')),
            ],
        ),
    ]
