# Generated by Django 3.2.8 on 2021-10-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one_question',
            name='type',
            field=models.CharField(choices=[('Autocomplete', 'Autocomplete'), ('Checkbox', 'Checkbox'), ('Chips', 'Chips'), ('Picker', 'Picker'), ('Radio', 'Radio'), ('Range', 'Range'), ('Select', 'Select'), ('Switch', 'Switch'), ('Input', 'Input'), ('Switch', 'Switch')], default='Input', max_length=20, verbose_name='type_choices'),
        ),
    ]
