# Generated by Django 3.2.8 on 2021-10-25 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='one_question',
            old_name='field_id',
            new_name='fid',
        ),
    ]
