# Generated by Django 3.2.8 on 2021-10-18 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='F101',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(blank=True, max_length=30, null=True)),
                ('describe', models.JSONField(blank=True, default=dict, null=True)),
                ('desire', models.JSONField(blank=True, max_length=350, null=True)),
                ('listen', models.CharField(blank=True, max_length=100, null=True)),
                ('teachable', models.IntegerField(blank=True, null=True)),
                ('willing', models.CharField(blank=True, max_length=70, null=True)),
                ('change', models.CharField(blank=True, max_length=350, null=True)),
                ('meeting', models.BigIntegerField(max_length=350)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
        ),
    ]
