# Generated by Django 3.2.8 on 2021-10-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('src', models.CharField(blank=True, max_length=30, null=True)),
                ('fname', models.CharField(blank=True, max_length=30, null=True)),
                ('lname', models.CharField(blank=True, max_length=30, null=True)),
                ('tel', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
